compile:
	cd n\=128 && go build main.go
	cd n\=256 && go build main.go
	cd n\=512 && go build main.go
	cd n\=1024 && go build main.go
	cd n\=2048 && go build main.go
	cd n\=4096 && go build main.go
	cd n\=8192 && go build main.go

remove:
	cd n\=128 && rm main
	cd n\=256 && rm main
	cd n\=512 && rm main
	cd n\=1024 && rm main
	cd n\=2048 && rm main
	cd n\=4096 && rm main
	cd n\=8192 && rm main
