compile:
	cd n\=128 && python3 main.py
	cd n\=256 && python3 main.py
	cd n\=512 && python3 main.py
	cd n\=1024 && python3 main.py
	cd n\=2048 && python3 main.py
	cd n\=4096 && python3 main.py
	cd n\=8192 && python3 main.py
