compile:
	cd n\=128 && gcc main.c -o main
	cd n\=256 && gcc main.c -o main
	cd n\=512 && gcc main.c -o main
	cd n\=1024 && gcc main.c -o main
	cd n\=2048 && gcc main.c -o main
	cd n\=4096 && gcc main.c -o main
	cd n\=8192 && gcc main.c -o main

remove:
	cd n\=128 && rm main
	cd n\=256 && rm main
	cd n\=512 && rm main
	cd n\=1024 && rm main
	cd n\=2048 && rm main
	cd n\=4096 && rm main
	cd n\=8192 && rm main
