compile:
	cd n\=128 && javac Subarraymax.java
	cd n\=256 && javac Subarraymax.java
	cd n\=512 && javac Subarraymax.java
	cd n\=1024 && javac Subarraymax.java
	cd n\=2048 && javac Subarraymax.java
	cd n\=4096 && javac Subarraymax.java
	cd n\=8192 && javac Subarraymax.java

remove:
	cd n\=128 && rm Subarraymax.class
	cd n\=256 && rm Subarraymax.class
	cd n\=512 && rm Subarraymax.class
	cd n\=1024 && rm Subarraymax.class
	cd n\=2048 && rm Subarraymax.class
	cd n\=4096 && rm Subarraymax.class
	cd n\=8192 && rm Subarraymax.class

